project:
  type: website
  output-dir: docs

website:
  title: "OurItalyInData.github.io"
  open-graph: true
  
  # stuff
  cookie-consent:
    type: express
    style: interstitial
  reader-mode: true
  back-to-top-navigation: true
  bread-crumbs: false
  
  # navigation bar
  navbar:
    background: primary
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/OurItalyInData/OurItalyInData.github.io
          - text: Report a Bug
            href: https://github.com/OurItalyInData/OurItalyInData.github.io/issues

    left:
      - text: "Home"
        href: index.qmd
      - sidebar:istat
      - sidebar:inps
      - sidebar:pnrr
      - sidebar:eurostat
      - sidebar:ecb
      - sidebar:fred
      - sidebar:oecd
      - sidebar:world_bank

  sidebar:
    - id: istat
      title: "ISTAT"
      style: "docked"
      background: light
      collapse-level: 2
      contents: topics/istat
    - id: eurostat
      title: "Eurostat"
      style: "docked"
      background: light
      collapse-level: 2
      contents: topics/eurostat
    - id: inps
      title: "INPS"
      style: "docked"
      background: light
      collapse-level: 2
      contents: topics/inps
    - id: pnrr
      title: "PNRR"
      style: "docked"
      background: light
      collapse-level: 2
      contents: topics/pnrr
    - id: ecb
      title: "ECB"
      style: "docked"
      background: light
      collapse-level: 2
      contents: topics/ecb
    - id: fred
      title: "FRED"
      style: "docked"
      background: light
      collapse-level: 2
      contents: topics/fred
    - id: oecd
      title: "OECD"
      style: "docked"
      background: light
      collapse-level: 2
      contents: topics/oecd
    - id: world_bank
      title: "WORLD BANK"
      style: "docked"
      background: light
      collapse-level: 2
      contents: topics/world_bank
    


# execute
execute:
  eval: true
  freeze: auto
  cache: false
  echo: true
  message: false
  warning: false

# format
format:
  html:
    theme:
      light: [flatly, theme_light_custom.scss] 
      dark: [darkly, theme_dark_custom.scss]
    code-link: TRUE
    code-fold: true
    code-line-numbers: TRUE
    code-copy: TRUE
    highlight-style: monokai
    toc: true

editor: visual
